quarkus.http.port=${PORT:8080}
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:rental_management}?stringtype=unspecified
quarkus.datasource.username=${DB_USER:postgres}
quarkus.datasource.password=${DB_PASSWORD:example}

quarkus.hibernate-orm.schema-management.strategy=none

quarkus.hibernate-orm.log.sql=true

quarkus.smallrye-openapi.info-title=API Gestión de Arriendos
quarkus.smallrye-openapi.info-description=Sistema central para la administración de propiedades y contratos
quarkus.smallrye-openapi.info-version=1.0.0